# Application properties for connecting to PostgresSQL database
spring.datasource.url=jdbc:postgresql://localhost:5433/pingpong
spring.datasource.username=justin
spring.datasource.password=password
# Spring Data REST properties
spring.data.rest.base-path=/api